---
- name: Install WordPress on EC2 Instance
  hosts: ec2_instance
  become: true
  vars:
    mysql_root_password: "your_mysql_root_password"
    wordpress_db_name: "your_wordpress_db_name"
    wordpress_db_user: "your_wordpress_db_user"
    wordpress_db_password: "your_wordpress_db_password"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP and other dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-cli
        - php-mysql
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml
        - unzip

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Install Python MySQL client
      apt:
        name: python3-mysqldb
        state: present

    - name: Check if Python MySQL client is installed
      command: "python3 -c 'import MySQLdb'"
      register: check_mysql
      failed_when: false
      changed_when: false

    - name: Secure MySQL Installation (optional, for production use)
      expect:
        command: "mysql_secure_installation"
        responses:
          "Press y|Y for Yes, any other key for No:": "Y\n"
          "Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG:": "0\n"
          "New password: ": "{{ mysql_root_password }}\n"
          "Re-enter new password: ": "{{ mysql_root_password }}\n"
          "Remove anonymous users? (Press y|Y for Yes, any other key for No) ": "Y\n"
          "Disallow root login remotely? (Press y|Y for Yes, any other key for No) ": "Y\n"
          "Remove test database and access to it? (Press y|Y for Yes, any other key for No) ": "Y\n"
          "Reload privilege tables now? (Press y|Y for Yes, any other key for No) ": "Y\n"
      become: true

    - name: Create MySQL Database for WordPress
      mysql_db:
        name: "{{ wordpress_db_name }}"
        state: present
      become: true
      when: "'The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required.' not in check_mysql.stderr"

    - name: Create MySQL User for WordPress
      mysql_user:
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_password }}"
        priv: "{{ wordpress_db_name }}.*:ALL"
        state: present
      become: true

    - name: Download WordPress archive
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress archive
      command: "tar -zxvf /tmp/wordpress.tar.gz -C /var/www/html/"
     
    - name: Set correct permissions for WordPress
      file:
        path: "/var/www/html/wordpress"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Configure WordPress wp-config.php
      template:
        src: wp-config.php.j2
        dest: "/var/www/html/wordpress/wp-config.php"
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
